server:
    port: 3335




pool-connection:
  ifood:
    datasource:
      jdbc-url: jdbc:mysql://localhost:3306/ifood?useSSL=false&serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver